services:
  postgres-fso:
    image: postgres
    container_name: postgres-fso
    volumes:
      - postgres-volume-fso:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cragtok
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    restart: always
  pgadmin-fso:
    image: dpage/pgadmin4
    container_name: pgadmin-fso
    depends_on:
      - postgres-fso
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: cragtok@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
    postgres-volume-fso:
        name: postgres-volume-fso

# psql -U cragtok postgres
